### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object when building animator

### ISSUE THREAD

**Issue by FizzyTaco** [seanedwards/vrc-worldobject#2]
I imported the unitypackage and then dragged the WorldObject prefab to the root of my scene. I then dragged it to the root of my avatar. I added the script to my avatar and pressed Build Animator. It didn't work and spat out this error. Im on the latest sdk and unity 2019.4.31f1. 
![Screenshot 2022-02-25 095434](https://user-images.githubusercontent.com/46660501/155755437-52d52baf-1715-4eba-b2d5-0a21bf2a9878.png)

I then tried it in a new project with only the sdk and the fbx of an avatar in it. It had new an entirely empty fx layer and fresh menu/parameters. I followed the same instructions and performed the same steps. And it spat out the exact same error when I pressed build animator. 

Both tests only seem to have gotten as far as adding the parameters. No layers got actually created. 
![GitScreen1](https://user-images.githubusercontent.com/46660501/155756024-680862b6-d0f1-407b-8ad5-21311bacda2c.png)
![GitScreen2](https://user-images.githubusercontent.com/46660501/155756038-ea999d25-d75a-4552-be8b-8e6510ba158b.png)

Here's the raw text of the error if you need it
> NullReferenceException: Object reference not set to an instance of an object
WorldObjectSetupEditor+<>c__DisplayClass8_0.<GetOrCreateClip>b__0 (UnityEngine.Object asset) (at Assets/vrc-worldobject/Editor/WorldObjectSetupEditor.cs:218)
System.Array.Find[T] (T[] array, System.Predicate`1[T] match) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
WorldObjectSetupEditor.GetOrCreateClip (UnityEditor.Animations.AnimatorController controller, UnityEngine.Object[] existingAssets, System.String name) (at Assets/vrc-worldobject/Editor/WorldObjectSetupEditor.cs:218)
WorldObjectSetupEditor.GenerateStateMachine (UnityEditor.Animations.AnimatorController controller, System.Boolean isFine, System.Single range) (at Assets/vrc-worldobject/Editor/WorldObjectSetupEditor.cs:135)
WorldObjectSetupEditor.GenerateWorldObject (System.Single range) (at Assets/vrc-worldobject/Editor/WorldObjectSetupEditor.cs:55)
WorldObjectSetupEditor.OnInspectorGUI () (at Assets/vrc-worldobject/Editor/WorldObjectSetupEditor.cs:29)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass58_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <a259d3c004024353a2c217da97495055>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by seanedwards** [comment]
Hey @FizzyTaco, thanks for the very thorough report. I'm having trouble reproducing the issue locally, but I do have an idea based on the info you provided. Could you try out this new version of `vrc-worldobject/Editor/WorldObjectSetupEditor.cs` and see if it fixes the issue? https://raw.githubusercontent.com/seanedwards/vrc-worldobject/main/Editor/WorldObjectSetupEditor.cs

**Comment by FizzyTaco** [comment]
@seanedwards Sorry that it took me a bit to get back. I tried the new script and it worked perfectly I think. No errors happened in the console and the animator got set up. Ty for the quick fix!
