### ISSUE TITLE
Add more Documentation

### ISSUE THREAD

**Issue by tschaerni** [seanedwards/vrc-worldobject#4]
Hi!

Awesome Idea, I also wanted to try something like that for a while now.
I'm at the moment disecting your project and I wondered if you may could provide a bit more documentation? Specifically what gets sent and received over OSC?
I suppose that you just send the values from the ingame parameters over OSC to TouchOSC and TouchOSC just reflects them back?
I also assume you can manipulate the values from inside TouchOSC? But that isn't needed, right?
The reason I ask is because I would like to write a python script that would replace TouchOSC, so I can have it running on my homeserver and don't have to think about it ;)

Cheers!

**Comment by seanedwards** [comment]
@tschaerni I actually wrote a doc about how that works here! https://docs.olivr.dev/avatars/parameter-multiplexing

I'll close this for now but feel free to re-open if that's not what you're looking for.
